ALTER TABLE licence
    ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE application
    ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE application_history
    ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
