CREATE TABLE revision_info
(
    revision_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    revision_timestamp BIGINT NOT NULL,
    PRIMARY KEY (revision_id)
);

CREATE TABLE application_history
(
    id                   BIGINT       NOT NULL,
    revision_id          BIGINT       NOT NULL,
    revision_type        SMALLINT,
    application_number   VARCHAR(255) NOT NULL,
    agency_id            BIGINT       NOT NULL,
    licence_type_id      BIGINT       NOT NULL,
    licence_name         VARCHAR(255) NOT NULL,
    status               VARCHAR(255) NOT NULL,
    submitted_date       TIMESTAMP    NOT NULL,
    transaction_type     VARCHAR(255) NOT NULL,
    apply_as             VARCHAR(255) NOT NULL,
    login_type           VARCHAR(255) NOT NULL,
    applicant            JSONB NULL,
    filer                JSONB NULL,
    company              JSONB NULL,
    licence_data_fields  JSONB NULL,
    form_meta_data       JSONB NULL,
    reviewer_id          BIGINT NULL,
    created_by           VARCHAR(255) NOT NULL,
    created_at           TIMESTAMP    NOT NULL,
    updated_by           VARCHAR(255) NOT NULL,
    updated_at           TIMESTAMP    NOT NULL,
    case_status          varchar(255) NOT NULL,
    applicant_name       VARCHAR(255) NOT NULL,
    internal_remarks     VARCHAR NULL,
    message_to_applicant VARCHAR NULL,
    PRIMARY KEY (id, revision_id)
);

ALTER TABLE application_history
    ADD CONSTRAINT fk_application_revision_info_rev_id FOREIGN KEY (revision_id) REFERENCES revision_info (revision_id);
